community=["all",
"activity partners",
"artists",
"childcare",
"general",
"groups",
"local news and views",
"lost & found",
"musicians",
"pets",
"politics",
"rideshare",
"volunteers",
]

events=["all",
"classes",
"events",
]

for_sale=["all",
"antiques",
"appliances",
"arts+crafts",
"atvs/utvs/snow",
"auto parts",
"baby+kids",
"barter",
"beauty+hlth",
"bike parts",
"bikes",
"boat parts",
"boats",
"books",
"business",
"cars+trucks",
"cds/dvd/vhs",
"cell phones",
"clothes+acc",
"collectibles",
"computer parts",
"computers",
"electronics",
"farm+garden",
"free stuff",
"furniture",
"garage sales",
"general",
"heavy equipment",
"household",
"jewelry",
"materials",
"motorcycle parts",
"motorcycles",
"music instr",
"photo+video",
"RVs",
"sporting",
"tickets",
"tools",
"toys+games",
"video gaming",
"wanted",
]

gigs=["all",
"computer gigs",
"creative gigs",
"crew gigs",
"domestic gigs",
"event gigs",
"labor gigs",
"talent gigs",
"writing gigs",
]

housing=["all",
"apts broker fee",
"apts broker no fee",
"apts by owner",
"apts registration fee",
"apts wanted",
"housing swap",
"office & commercial",
"parking & storage",
"real estate - by broker",
"real estate - by owner",
"real estate wanted",
"rooms & shares",
"rooms wanted",
"sublet/temp wanted",
"sublets & temporary",
"vacation rentals",
"all bedrooms",
"1+ bedrooms",
"2+ bedrooms",
"3+ bedrooms",
"4+ bedrooms",
"5+ bedrooms",
"6+ bedrooms",
"7+ bedrooms",
"8+ bedrooms",
"all bathrooms",
"1+ bathrooms",
"2+ bathrooms",
"3+ bathrooms",
"4+ bathrooms",
"5+ bathrooms",
"6+ bathrooms",
"7+ bathrooms",
"8+ bathrooms",
]

jobs=["all",
"admin/office",
"business",
"customer service",
"education",
"engineering",
"etcetera",
"finance",
"food/bev/hosp",
"general labor",
"government",
"healthcare",
"human resource",
"internet engineering",
"legal",
"manufacturing",
"marketing",
"media",
"nonprofit",
"real estate",
"retail/wholesale",
"sales",
"salon/spa/fitness",
"science",
"security",
"skilled trades",
"software",
"systems/networking",
"tech support",
"transport",
"tv video radio",
"web design",
"writing",
]

personals=["all",
"casual encounters",
"men seeking men",
"men seeking women",
"misc romance",
"missed connections",
"rants & raves",
"strictly platonic",
"women seeking men",
"women seeking women",
]

resumes=[]

services=["all",
"automotive services",
"beauty services",
"computer services",
"creative services",
"cycle services",
"event services",
"farm & garden services",
"financial services",
"household services",
"labor & moving",
"legal services",
"lessons & tutoring",
"marine services",
"pet services",
"real estate services",
"skilled trade services",
"small biz ads",
"therapeutic services",
"travel/vacation",
"write/edit/trans",
]

