section=[("community","http://boston.craigslist.org/search/ccc"),
         ("events","http://boston.craigslist.org/search/eee"),
         ("for sale","http://boston.craigslist.org/search/sss"),
         ("gigs","http://boston.craigslist.org/search/ggg"),
         ("housing","http://boston.craigslist.org/search/hhh"),
         ("jobs","http://boston.craigslist.org/search/jjj"),
         ("personals","http://boston.craigslist.org/search/ppp"),
         ("resumes","http://boston.craigslist.org/search/rrr"),
         ("services","http://boston.craigslist.org/search/bbb")]

community = [("all","ccc"),
("activity partners","act"),
("artists","ats"),
("childcare","kid"),
("general","com"),
("groups","grp"),
("local news and views","vnn"),
("lost & found","laf"),
("musicians","muc"),
("pets","pet"),
("politics","pol"),
("rideshare","rid"),
("volunteers","vol")]

for_sale = [("all","sss"),
("antiques","ata"),
("appliances","ppa"),
("arts+crafts","ara"),
("atvs/utvs/snow","sna"),
("auto parts","pta"),
("baby+kids","baa"),
("barter","bar"),
("beauty+hlth","haa"),
("bike parts","bip"),
("bikes","bia"),
("boat parts","bpa"),
("boats","boo"),
("books","bka"),
("business","bfa"),
("cars+trucks","cta"),
("cds/dvd/vhs","ema"),
("cell phones","moa"),
("clothes+acc","cla"),
("collectibles","cba"),
("computer parts","syp"),
("computers","sya"),
("electronics","ela"),
("farm+garden","gra"),
("free stuff","zip"),
("furniture","fua"),
("garage sales","gms"),
("general","foa"),
("heavy equipment","hva"),
("household","hsa"),
("jewelry","jwa"),
("materials","maa"),
("motorcycle parts","mpa"),
("motorcycles","mca"),
("music instr","msa"),
("photo+video","pha"),
("RVs","rva"),
("sporting","sga"),
("tickets","tia"),
("tools","tla"),
("toys+games","taa"),
("video gaming","vga"),
("wanted","waa")]

housing = [("all","hhh"),
("apts broker fee","fee"),
("apts broker no fee","nfb"),
("apts by owner","abo"),
("apts registration fee","aiv"),
("apts wanted","hou"),
("housing swap","swp"),
("office & commercial","off"),
("parking & storage","prk"),
("real estate - by broker","reb"),
("real estate - by owner","reo"),
("real estate wanted","rew"),
("rooms & shares","roo"),
("rooms wanted","sha"),
("sublet/temp wanted","sbw"),
("sublets & temporary","sub"),
("vacation rentals","vac"),
("all bedrooms",""),
("1+ bedrooms","1"),
("2+ bedrooms","2"),
("3+ bedrooms","3"),
("4+ bedrooms","4"),
("5+ bedrooms","5"),
("6+ bedrooms","6"),
("7+ bedrooms","7"),
("8+ bedrooms","8"),
("all bathrooms",""),
("1+ bathrooms","1"),
("2+ bathrooms","2"),
("3+ bathrooms","3"),
("4+ bathrooms","4"),
("5+ bathrooms","5"),
("6+ bathrooms","6"),
("7+ bathrooms","7"),
("8+ bathrooms","8")]

events = [
("all","eee"),
("classes","cls"),
("events","eve")]

gigs = [("all","ggg"),
("computer gigs","cpg"),
("creative gigs","crg"),
("crew gigs","cwg"),
("domestic gigs","dmg"),
("event gigs","evg"),
("labor gigs","lbg"),
("talent gigs","tlg"),
("writing gigs","wrg")]

jobs = [("all","jjj"),
("admin/office","ofc"),
("business","bus"),
("customer service","csr"),
("education","edu"),
("engineering","egr"),
("etcetera","etc"),
("finance","acc"),
("food/bev/hosp","fbh"),
("general labor","lab"),
("government","gov"),
("healthcare","hea"),
("human resource","hum"),
("internet engineering","eng"),
("legal","lgl"),
("manufacturing","mnu"),
("marketing","mar"),
("media","med"),
("nonprofit","npo"),
("real estate","rej"),
("retail/wholesale","ret"),
("sales","sls"),
("salon/spa/fitness","spa"),
("science","sci"),
("security","sec"),
("skilled trades","trd"),
("software","sof"),
("systems/networking","sad"),
("tech support","tch"),
("transport","trp"),
("tv video radio","tfr"),
("web design","web"),
("writing","wri")]

personals = [("all","ppp"),
("casual encounters","cas"),
("men seeking men","m4m"),
("men seeking women","m4w"),
("misc romance","msr"),
("missed connections","mis"),
("rants & raves","rnr"),
("strictly platonic","stp"),
("women seeking men","w4m"),
("women seeking women","w4w")]

services = [("all","bbb"),
("automotive services","aos"),
("beauty services","bts"),
("computer services","cps"),
("creative services","crs"),
("cycle services","cys"),
("event services","evs"),
("farm & garden services","fgs"),
("financial services","fns"),
("household services","hss"),
("labor & moving","lbs"),
("legal services","lgs"),
("lessons & tutoring","lss"),
("marine services","mas"),
("pet services","pas"),
("real estate services","rts"),
("skilled trade services","sks"),
("small biz ads","biz"),
("therapeutic services","thp"),
("travel/vacation","trv"),
("write/edit/trans","wet"),
]
